"""
Sirius BIST - Hisse Listeleri
Kaynak: KAP - Borsa Istanbul resmi endeks listesi
Guncelleme tarihi: 2026-05
"""

# BIST KATILIM TUM - 237 hisse
# Katilim finans uyumlu Borsa Istanbul hisseleri
BIST_KATILIM = [
    "AAGYO", "ACSEL", "AHGAZ", "AHSGY", "AKFYE",
    "AKHAN", "ALBRK", "ALCTL", "ALFAS", "ALKA",
    "ALKIM", "ALKLC", "ALTNY", "ALVES", "ANGEN",
    "ARASE", "ARDYZ", "ARENA", "ARFYE", "ASELS",
    "ATAKP", "ATATP", "AVPGY", "AYEN", "BAHKM",
    "BAKAB", "BASGZ", "BAYRK", "BEGYO", "BERA",
    "BESTE", "BIENY", "BIMAS", "BINBN", "BINHO",
    "BMSTL", "BORSK", "BOSSA", "BRISA", "BRKSN",
    "BRLSM", "BSOKE", "BUCIM", "BURCE", "BURVA",
    "BYDNR", "CANTE", "CATES", "CELHA", "CEMTS",
    "CEMZY", "CIMSA", "CMBTN", "COSMO", "CVKMD",
    "CWENE", "DAPGM", "DARDL", "DCTTR", "DENGE",
    "DESPC", "DGATE", "DITAS", "DMSAS", "DNISI",
    "DOFER", "DOFRB", "DOGUB", "DYOBY", "EBEBK",
    "EDATA", "EDIP", "EFOR", "EGEPO", "EGGUB",
    "EGPRO", "EKGYO", "EKSUN", "ELITE", "EMPAE",
    "ENJSA", "EREGL", "ESCOM", "EUPWR", "EYGYO",
    "FADE", "FONET", "FORMT", "FORTE", "FRMPL",
    "FZLGY", "GEDZA", "GENIL", "GENKM", "GENTS",
    "GEREL", "GESAN", "GLRMK", "GMTAS", "GOKNR",
    "GOLTS", "GOODY", "GRSEL", "GRTHO", "GUBRF",
    "GUNDG", "HATSN", "HKTM", "HOROZ", "HRKET",
    "IDGYO", "IHEVA", "IHLAS", "IHLGM", "IHYAY",
    "IMASM", "INGRM", "INTEM", "ISDMR", "IZFAS",
    "IZINV", "JANTS", "KARSN", "KATMR", "KBORU",
    "KCAER", "KIMMR", "KLSER", "KLSYN", "KMPUR",
    "KNFRT", "KOCMT", "KONKA", "KONYA", "KOPOL",
    "KOTON", "KRDMA", "KRDMB", "KRDMD", "KRGYO",
    "KRONT", "KRPLS", "KRSTL", "KRVGD", "KTLEV",
    "KUTPO", "KZBGY", "LKMNH", "LMKDC", "LOGO",
    "LXGYO", "MAGEN", "MAKIM", "MARBL", "MAVI",
    "MCARD", "MEDTR", "MEGMT", "MEKAG", "MERCN",
    "MERKO", "MEYSU", "MNDTR", "MOBTL", "MOPAS",
    "MPARK", "NETAS", "NETCD", "NTGAZ", "OBAMS",
    "OBASE", "ONCSM", "ORGE", "OSTIM", "OZATD",
    "OZGYO", "OZRDN", "OZYSR", "PAGYO", "PARSN",
    "PASEU", "PENGD", "PENTA", "PETKM", "PKART",
    "PLTUR", "PNSUT", "POLHO", "PRKME", "QUAGR",
    "RALYH", "RGYAS", "RNPOL", "RODRG", "RUBNS",
    "SAFKR", "SAMAT", "SANEL", "SANKO", "SARKY",
    "SAYAS", "SDTTR", "SEKUR", "SELEC", "SELVA",
    "SILVR", "SMART", "SNGYO", "SNICA", "SOKE",
    "SRVGY", "SUNTK", "SURGY", "SUWEN", "TARKM",
    "TEZOL", "TKFEN", "TKNSA", "TMPOL", "TUCLK",
    "TUKAS", "TUPRS", "TUREX", "TURGG", "UCAYM",
    "UFUK", "ULUSE", "USAK", "VAKKO", "VANGD",
    "YATAS", "YEOTK", "YIGIT", "YKSLN", "YUNSA",
    "ZEDUR", "ZERGY",
]

# BIST TUM - 568 hisse
# Borsa Istanbul tum hisseleri
BIST_TUM = [
    "A1CAP", "A1YEN", "AAGYO", "ACSEL", "ADEL",
    "ADESE", "ADGYO", "AEFES", "AFYON", "AGESA",
    "AGHOL", "AGROT", "AGYO", "AHGAZ", "AHSGY",
    "AKBNK", "AKCNS", "AKENR", "AKFGY", "AKFIS",
    "AKFYE", "AKGRT", "AKHAN", "AKMGY", "AKSA",
    "AKSEN", "AKSGY", "AKSUE", "AKYHO", "ALARK",
    "ALBRK", "ALCAR", "ALCTL", "ALFAS", "ALGYO",
    "ALKA", "ALKIM", "ALKLC", "ALTNY", "ALVES",
    "ANELE", "ANGEN", "ANHYT", "ANSGR", "ARASE",
    "ARCLK", "ARDYZ", "ARENA", "ARFYE", "ARMGD",
    "ARSAN", "ARTMS", "ARZUM", "ASELS", "ASGYO",
    "ASTOR", "ASUZU", "ATAGY", "ATAKP", "ATATP",
    "ATATR", "AVGYO", "AVHOL", "AVOD", "AVPGY",
    "AVTUR", "AYCES", "AYDEM", "AYEN", "AYGAZ",
    "AZTEK", "BAGFS", "BAHKM", "BAKAB", "BALSU",
    "BANVT", "BARMA", "BASGZ", "BAYRK", "BEGYO",
    "BERA", "BESLR", "BESTE", "BEYAZ", "BFREN",
    "BIENY", "BIGCH", "BIGEN", "BIGTK", "BIMAS",
    "BINBN", "BINHO", "BIOEN", "BIZIM", "BJKAS",
    "BLCYT", "BLUME", "BMSCH", "BMSTL", "BNTAS",
    "BOBET", "BORLS", "BORSK", "BOSSA", "BRISA",
    "BRKSN", "BRKVY", "BRLSM", "BRSAN", "BRYAT",
    "BSOKE", "BTCIM", "BUCIM", "BULGS", "BURCE",
    "BURVA", "BVSAN", "BYDNR", "CANTE", "CATES",
    "CCOLA", "CELHA", "CEMAS", "CEMTS", "CEMZY",
    "CEOEM", "CGCAM", "CIMSA", "CLEBI", "CMBTN",
    "CONSE", "COSMO", "CRDFA", "CRFSA", "CUSAN",
    "CVKMD", "CWENE", "DAGI", "DAPGM", "DARDL",
    "DCTTR", "DENGE", "DERHL", "DERIM", "DESA",
    "DESPC", "DEVA", "DGATE", "DGGYO", "DGNMO",
    "DITAS", "DMRGD", "DMSAS", "DNISI", "DOAS",
    "DOCO", "DOFER", "DOFRB", "DOGUB", "DOHOL",
    "DOKTA", "DSTKF", "DUNYH", "DURDO", "DURKN",
    "DYOBY", "DZGYO", "EBEBK", "ECILC", "ECOGR",
    "ECZYT", "EDATA", "EDIP", "EFOR", "EGEEN",
    "EGEGY", "EGEPO", "EGGUB", "EGPRO", "EGSER",
    "EKDMR", "EKGYO", "EKOS", "EKSUN", "ELITE",
    "EMKEL", "EMPAE", "ENDAE", "ENERY", "ENJSA",
    "ENKAI", "ENSRI", "ENTRA", "EPLAS", "ERBOS",
    "ERCB", "EREGL", "ERSU", "ESCAR", "ESCOM",
    "ESEN", "ETILR", "EUPWR", "EUREN", "EYGYO",
    "FADE", "FENER", "FLAP", "FMIZP", "FONET",
    "FORMT", "FORTE", "FRIGO", "FRMPL", "FROTO",
    "FZLGY", "GARAN", "GARFA", "GEDIK", "GEDZA",
    "GENIL", "GENKM", "GENTS", "GEREL", "GESAN",
    "GIPTA", "GLBMD", "GLCVY", "GLRMK", "GLRYH",
    "GLYHO", "GMTAS", "GOKNR", "GOLTS", "GOODY",
    "GOZDE", "GRSEL", "GRTHO", "GSDDE", "GSDHO",
    "GSRAY", "GUBRF", "GUNDG", "GWIND", "GZNMI",
    "HALKB", "HATEK", "HATSN", "HDFGS", "HEDEF",
    "HEKTS", "HKTM", "HLGYO", "HOROZ", "HRKET",
    "HTTBT", "HUBVC", "HUNER", "HURGZ", "ICBCT",
    "ICUGS", "IDGYO", "IEYHO", "IHAAS", "IHEVA",
    "IHGZT", "IHLAS", "IHLGM", "IHYAY", "IMASM",
    "INDES", "INFO", "INGRM", "INTEM", "INVEO",
    "INVES", "ISATR", "ISBTR", "ISCTR", "ISDMR",
    "ISFIN", "ISGSY", "ISGYO", "ISKPL", "ISMEN",
    "ISSEN", "IZENR", "IZFAS", "IZINV", "IZMDC",
    "JANTS", "KAPLM", "KAREL", "KARSN", "KARTN",
    "KATMR", "KAYSE", "KBORU", "KCAER", "KCHOL",
    "KFEIN", "KGYO", "KIMMR", "KLGYO", "KLKIM",
    "KLMSN", "KLRHO", "KLSER", "KLSYN", "KLYPV",
    "KMPUR", "KNFRT", "KOCMT", "KONKA", "KONTR",
    "KONYA", "KOPOL", "KORDS", "KOTON", "KRDMA",
    "KRDMB", "KRDMD", "KRGYO", "KRONT", "KRPLS",
    "KRSTL", "KRTEK", "KRVGD", "KTLEV", "KTSKR",
    "KUTPO", "KUVVA", "KUYAS", "KZBGY", "KZGYO",
    "LIDER", "LIDFA", "LILAK", "LINK", "LKMNH",
    "LMKDC", "LOGO", "LRSHO", "LUKSK", "LXGYO",
    "LYDHO", "LYDYE", "MAALT", "MACKO", "MAGEN",
    "MAKIM", "MAKTK", "MANAS", "MARBL", "MARKA",
    "MARMR", "MARTI", "MAVI", "MCARD", "MEDTR",
    "MEGMT", "MEKAG", "MEPET", "MERCN", "MERIT",
    "MERKO", "METRO", "MEYSU", "MGROS", "MHRGY",
    "MIATK", "MNDRS", "MNDTR", "MOBTL", "MOGAN",
    "MOPAS", "MPARK", "MRGYO", "MRSHL", "MSGYO",
    "MTRKS", "MZHLD", "NATEN", "NETAS", "NETCD",
    "NIBAS", "NTGAZ", "NTHOL", "NUGYO", "NUHCM",
    "OBAMS", "OBASE", "ODAS", "ODINE", "OFSYM",
    "ONCSM", "ONRYT", "ORCAY", "ORGE", "OSMEN",
    "OSTIM", "OTKAR", "OTTO", "OYAKC", "OYLUM",
    "OYYAT", "OZATD", "OZGYO", "OZKGY", "OZRDN",
    "OZSUB", "OZYSR", "PAGYO", "PAHOL", "PAMEL",
    "PAPIL", "PARSN", "PASEU", "PATEK", "PCILT",
    "PEKGY", "PENGD", "PENTA", "PETKM", "PETUN",
    "PGSUS", "PINSU", "PKART", "PKENT", "PLTUR",
    "PNLSN", "PNSUT", "POLHO", "POLTK", "PRDGS",
    "PRKAB", "PRKME", "PRZMA", "PSDTC", "PSGYO",
    "QUAGR", "RALYH", "RAYSG", "REEDR", "RGYAS",
    "RNPOL", "RODRG", "RTALB", "RUBNS", "RUZYE",
    "RYGYO", "RYSAS", "SAFKR", "SAHOL", "SAMAT",
    "SANEL", "SANFM", "SANKO", "SARKY", "SASA",
    "SAYAS", "SDTTR", "SEGMN", "SEGYO", "SEKFK",
    "SEKUR", "SELEC", "SELVA", "SERNT", "SEYKM",
    "SILVR", "SISE", "SKBNK", "SKTAS", "SKYLP",
    "SKYMD", "SMART", "SMRTG", "SMRVA", "SNGYO",
    "SNICA", "SOKE", "SOKM", "SONME", "SRVGY",
    "SUNTK", "SURGY", "SUWEN", "SVGYO", "TABGD",
    "TARKM", "TATEN", "TATGD", "TAVHL", "TBORG",
    "TCELL", "TCKRC", "TDGYO", "TEHOL", "TEKTU",
    "TERA", "TEZOL", "TGSAS", "THYAO", "TKFEN",
    "TKNSA", "TLMAN", "TMPOL", "TMSN", "TNZTP",
    "TOASO", "TRALT", "TRCAS", "TRENJ", "TRGYO",
    "TRHOL", "TRILC", "TRMET", "TSGYO", "TSKB",
    "TSPOR", "TTKOM", "TTRAK", "TUCLK", "TUKAS",
    "TUPRS", "TUREX", "TURGG", "TURSG", "UCAYM",
    "UFUK", "ULAS", "ULKER", "ULUFA", "ULUSE",
    "ULUUN", "UNLU", "USAK", "VAKBN", "VAKFA",
    "VAKFN", "VAKKO", "VANGD", "VBTYZ", "VERTU",
    "VERUS", "VESBE", "VESTL", "VKGYO", "VKING",
    "VRGYO", "VSNMD", "YAPRK", "YATAS", "YAYLA",
    "YEOTK", "YESIL", "YGGYO", "YIGIT", "YKBNK",
    "YKSLN", "YUNSA", "YYLGD", "ZEDUR", "ZERGY",
    "ZGYO", "ZOREN", "ZRGYO",
]

# Hizli kontrol icin set versiyonlari
BIST_KATILIM_SET = set(BIST_KATILIM)
BIST_TUM_SET = set(BIST_TUM)

# Kullanim ornekleri:
# from bist_hisseler import BIST_KATILIM, BIST_TUM
# print(f"Katilim: {len(BIST_KATILIM)} hisse")
# print(f"Tum:     {len(BIST_TUM)} hisse")
